name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          DOCKER_REGISTRY_URL=${{ secrets.DOCKER_REGISTRY_URL }}
          DOCKER_REGISTRY_URL=${DOCKER_REGISTRY_URL%/}
          docker build -t $DOCKER_REGISTRY_URL/docker-nodejs:latest -f Dockerfile.prod .

      - name: Push Docker image
        run: |
          DOCKER_REGISTRY_URL=${{ secrets.DOCKER_REGISTRY_URL }}
          DOCKER_REGISTRY_URL=${DOCKER_REGISTRY_URL%/}
          docker push $DOCKER_REGISTRY_URL/docker-nodejs:latest
