name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_REGISTRY_URL }}/your-image-name:latest -f Dockerfile.prod .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_REGISTRY_URL }}/your-image-name:latest
